/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package order.controller;

import java.awt.Color;
import java.awt.Component;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.ListCellRenderer;
import order.model.OrderProduct;

/**
 *
 * @author Hoang
 */
public class OrderProductComboBoxRenderer extends JPanel implements ListCellRenderer<OrderProduct> {

    /**
     * Creates new form NewJPanel
     */
    public OrderProductComboBoxRenderer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbBranch = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        lbStock = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setPreferredSize(new java.awt.Dimension(450, 25));

        lbBranch.setText("Nokia");
        lbBranch.setPreferredSize(new java.awt.Dimension(138, 25));

        lbName.setText("Nokia Lumia 910 multimedia");
        lbName.setPreferredSize(new java.awt.Dimension(182, 25));

        lbStock.setText("Stock: 0");
        lbStock.setPreferredSize(new java.awt.Dimension(51, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbName, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbStock, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lbBranch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lbStock, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbBranch;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbStock;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getListCellRendererComponent(JList<? extends OrderProduct> list, OrderProduct value, int index, boolean isSelected, boolean cellHasFocus) {
        if (value != null) {
            int stock = value.getProStock();
            if (isSelected) {
                setBackground(Color.ORANGE);
                if (stock == 0) {
                    lbBranch.setForeground(Color.RED);
                    lbName.setForeground(Color.RED);
                    lbStock.setForeground(Color.RED);
                } else {
                    lbBranch.setForeground(Color.BLACK);
                    lbName.setForeground(Color.BLACK);
                    lbStock.setForeground(Color.BLACK);
                }
            } else {
                setBackground(new java.awt.Color(51, 51, 51));
                if (stock == 0) {
                    lbBranch.setForeground(Color.RED);
                    lbName.setForeground(Color.RED);
                    lbStock.setForeground(Color.RED);
                } else {
                    lbBranch.setForeground(list.getForeground());
                    lbName.setForeground(list.getForeground());
                    lbStock.setForeground(list.getForeground());
                }
            }

            lbBranch.setText(value.getBraName());
            lbName.setText(value.getProName());
            lbStock.setText("Stock: " + value.getProStock());

            if (index == -1) {
                if (stock == 0) {
                    lbBranch.setForeground(Color.RED);
                    lbName.setForeground(Color.RED);
                    lbStock.setForeground(Color.RED);
                } else {
                    lbBranch.setForeground(Color.ORANGE);
                    lbName.setForeground(Color.ORANGE);
                    lbStock.setForeground(Color.ORANGE);
                }
            }
        }
        return this;
    }
}
