/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.controller;

import java.awt.CardLayout;
import main.model.Login;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import main.model.UserFunction;
import utility.IOUtils;
import utility.SwingUtils;

/**
 * Man hinh login
 * 
 * @author Hoang
 */
public class LoginFrame extends javax.swing.JFrame {

    public static Login config;

    public static final String LOGIN_PANEL = "LoginPanel";
    public static final String CONFIG_PANEL = "ConfigPanel";
    public static final String CONFIG_FILENAME = "config";

    /**
     * Creates new form TestFrame
     */
    public LoginFrame() {
        // Thiet lap GUI
        initComponents();
        pnContent.add(new LoginPanel(this), LOGIN_PANEL);
        pnContent.add(new ConfigPanel(this), CONFIG_PANEL);
        reloadContentPanel(LOGIN_PANEL);

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                exit();
            }
        });
    }

    /**
     *  Check permission of user
     * 
     * @param userFunction
     * @return true if user has that permission
     */
    public static boolean checkPermission(UserFunction userFunction) {
        boolean result = false;
        for (UserFunction uf : config.userFunctions) {
            if (uf.FunctionGroup.equals(userFunction.FunctionGroup) && uf.FunctionName.equals(userFunction.FunctionName)) {
                result = true;
                break;
            }
        }
        return result;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Login System");
        setMinimumSize(new java.awt.Dimension(269, 554));
        setResizable(false);

        pnContent.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnContent, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnContent, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                // Khoi tao LAF
                SwingUtils.createLookAndFeel();

                // Load config tu file len, neu file khong ton tai thi tao moi
                try {
                    config = (Login) IOUtils.readObject(CONFIG_FILENAME);
                } catch (Exception e) {
                    // neu bi loi doc file thi config van la null
                    config = null;
                }

                if (config == null) { // Neu file config khong ton tai
                    config = new Login(Login.HOST, Login.PORT, Login.DBNAME, Login.NAME, Login.PASSWORD, Login.USER_NAME, Login.USER_PASSWORD, Login.USER_FUNCTIONS);
                    new LoginFrame().setVisible(true);
                } else { // Neu file config da ton tai
                    new MainFrame().setVisible(true);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnContent;
    // End of variables declaration//GEN-END:variables

    public void reloadContentPanel(String panelName) {
        CardLayout cl = (CardLayout) pnContent.getLayout();
        cl.show(pnContent, panelName);
    }

    public void exit() {
        if (SwingUtils.showConfirmDialog("Are you sure to exit?") == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }
}
