/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inbound.controller;


import java.awt.Color;
import java.awt.Component;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.ListCellRenderer;
import inbound.model.Supplier;





/**
 *
 * @author tuan
 */
public class InDetailSupplierComboBoxRenderer extends JPanel implements ListCellRenderer<Supplier> {

    /**
     * Creates new form NewJPanel
     */
    public InDetailSupplierComboBoxRenderer() {
        initComponents();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbId = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        lbAddress = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setPreferredSize(new java.awt.Dimension(800, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbId, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(lbName, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addGap(66, 66, 66)
                .addComponent(lbAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbId, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lbAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbName, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbAddress;
    private javax.swing.JLabel lbId;
    private javax.swing.JLabel lbName;
    // End of variables declaration//GEN-END:variables

    

   

    @Override
    public Component getListCellRendererComponent(JList<? extends Supplier> list, Supplier value, int index, boolean isSelected, boolean cellHasFocus) {
        if (value != null) {
            if (isSelected) {
                setBackground(Color.ORANGE);
                lbId.setForeground(Color.BLACK);
                lbName.setForeground(Color.BLACK);
                
                lbAddress.setForeground(Color.BLACK);
            } else {
                setBackground(new java.awt.Color(51, 51, 51));
                lbId.setForeground(list.getForeground());
                lbName.setForeground(list.getForeground());
                
                lbAddress.setForeground(list.getForeground());
            }
            
            lbId.setText(value.getSupID() + "");
            lbName.setText(value.getSupName());
            
            lbAddress.setText(value.getSupAddress());
            
            if (index == -1) {
                lbId.setForeground(Color.ORANGE);
                lbName.setForeground(Color.ORANGE);
                
                lbAddress.setForeground(Color.ORANGE);
            }
        }
        return this;
    }
}
