/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user.controller;

import employee.model.EmployeeSwingUtils;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import main.controller.LoginFrame;
import main.model.UserFunction;
import user.model.Permission;
import user.model.PermissionDAOImpl;
import user.model.User;
import utility.SwingUtils;

/**
 *
 * @author BonBon
 */
public class PermissionDialog extends javax.swing.JDialog {

    User user;
    Permission permission;
    PermissionDAOImpl permissionDAOImpl;
    List<Permission> perList = new ArrayList<>();
    List<Permission> perList1 = new ArrayList<>();
    boolean oldUser, oldPermission;

    //<editor-fold defaultstate="collapsed" desc="Constructor">
    /**
     * Creates new form PermissionDialog
     */
    public PermissionDialog(User user) {
        super((JFrame) null, true);
        initComponents();
        setLocationRelativeTo(null);
        this.user = user;
        lblID1.setText(user.getUserName() + "");

        //Lay data
        permissionDAOImpl = new PermissionDAOImpl(user.getUserID());
        perList = permissionDAOImpl.getList();
        setCheckBox();
        oldUser = userUpdate.isSelected();
        oldPermission = permissionUpdate.isSelected();

        if (!LoginFrame.checkPermission(new UserFunction(UserFunction.FG_PERMISSION, UserFunction.FN_UPDATE))) {
            setButton(false);
            setCheckBoxEnable(false);
        } else if (user.getUserName().equals(LoginFrame.config.userName)) {
            setButton(false);
            setCheckBoxEnable(false);
        } else if ((userUpdate.isSelected() == true || permissionUpdate.isSelected() == true) && (!LoginFrame.config.userName.equals("root"))) {
            setButton(false);
            setCheckBoxEnable(false);
        } else {
            setButton(false);
            btSelectAll.setEnabled(true);
            btDeselectAll.setEnabled(true);
        }

    }

    //</editor-fold>
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btSave = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        userUpdate = new javax.swing.JCheckBox();
        userView = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        productUpdate = new javax.swing.JCheckBox();
        productView = new javax.swing.JCheckBox();
        outbound = new javax.swing.JPanel();
        outboundUpdate = new javax.swing.JCheckBox();
        outboundView = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        inboundUpdate = new javax.swing.JCheckBox();
        inboundView = new javax.swing.JCheckBox();
        jPanel8 = new javax.swing.JPanel();
        branchUpdate = new javax.swing.JCheckBox();
        branchView = new javax.swing.JCheckBox();
        jPanel10 = new javax.swing.JPanel();
        cusUpdate = new javax.swing.JCheckBox();
        cusView = new javax.swing.JCheckBox();
        jPanel13 = new javax.swing.JPanel();
        saleoffUpdate = new javax.swing.JCheckBox();
        saleoffView = new javax.swing.JCheckBox();
        jPanel14 = new javax.swing.JPanel();
        orderUpdate = new javax.swing.JCheckBox();
        orderView = new javax.swing.JCheckBox();
        jPanel16 = new javax.swing.JPanel();
        salaryUpdate = new javax.swing.JCheckBox();
        salaryView = new javax.swing.JCheckBox();
        jPanel22 = new javax.swing.JPanel();
        serviceUpdate = new javax.swing.JCheckBox();
        serviceView = new javax.swing.JCheckBox();
        jPanel23 = new javax.swing.JPanel();
        cusLevelUpdate = new javax.swing.JCheckBox();
        cusLevelView = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        permissionUpdate = new javax.swing.JCheckBox();
        permissionView = new javax.swing.JCheckBox();
        lblID1 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        empUpdate = new javax.swing.JCheckBox();
        empView = new javax.swing.JCheckBox();
        jPanel26 = new javax.swing.JPanel();
        supplierUpdate = new javax.swing.JCheckBox();
        supplierView = new javax.swing.JCheckBox();
        btClose = new javax.swing.JButton();
        btSelectAll = new javax.swing.JButton();
        btDeselectAll = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Permission");
        setMaximumSize(new java.awt.Dimension(494, 439));
        setMinimumSize(new java.awt.Dimension(494, 439));
        setResizable(false);

        btSave.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/order/OK2.png"))); // NOI18N
        btSave.setText("Save");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });

        btCancel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/order/Cancel2.png"))); // NOI18N
        btCancel.setText("Cancel");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 153, 0))); // NOI18N

        userUpdate.setText("Update");
        userUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userUpdateActionPerformed(evt);
            }
        });

        userView.setText("View");
        userView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(userView, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userView)
                    .addComponent(userUpdate))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Product", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 153, 0))); // NOI18N

        productUpdate.setText("Update");
        productUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productUpdateActionPerformed(evt);
            }
        });

        productView.setText("View");
        productView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(productView, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(productUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productView)
                    .addComponent(productUpdate))
                .addContainerGap())
        );

        outbound.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Outbound", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 153, 0))); // NOI18N

        outboundUpdate.setText("Update");
        outboundUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outboundUpdateActionPerformed(evt);
            }
        });

        outboundView.setText("View");
        outboundView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outboundViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout outboundLayout = new javax.swing.GroupLayout(outbound);
        outbound.setLayout(outboundLayout);
        outboundLayout.setHorizontalGroup(
            outboundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, outboundLayout.createSequentialGroup()
                .addComponent(outboundView, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(outboundUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        outboundLayout.setVerticalGroup(
            outboundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outboundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(outboundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outboundView)
                    .addComponent(outboundUpdate))
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inbound", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 153, 0))); // NOI18N

        inboundUpdate.setText("Update");
        inboundUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inboundUpdateActionPerformed(evt);
            }
        });

        inboundView.setText("View");
        inboundView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inboundViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(inboundView, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inboundUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inboundView)
                    .addComponent(inboundUpdate))
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Branch", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 153, 0))); // NOI18N

        branchUpdate.setText("Update");
        branchUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branchUpdateActionPerformed(evt);
            }
        });

        branchView.setText("View");
        branchView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branchViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(branchView, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(branchUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(branchView)
                    .addComponent(branchUpdate))
                .addContainerGap())
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 153, 0))); // NOI18N

        cusUpdate.setText("Update");
        cusUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusUpdateActionPerformed(evt);
            }
        });

        cusView.setText("View");
        cusView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addComponent(cusView, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cusUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cusView)
                    .addComponent(cusUpdate))
                .addContainerGap())
        );

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SaleOff", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 153, 0))); // NOI18N

        saleoffUpdate.setText("Update");
        saleoffUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleoffUpdateActionPerformed(evt);
            }
        });

        saleoffView.setText("View");
        saleoffView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleoffViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addComponent(saleoffView, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saleoffUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saleoffView)
                    .addComponent(saleoffUpdate))
                .addContainerGap())
        );

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Order", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 153, 0))); // NOI18N

        orderUpdate.setText("Update");
        orderUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderUpdateActionPerformed(evt);
            }
        });

        orderView.setText("View");
        orderView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addComponent(orderView, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(orderUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderView)
                    .addComponent(orderUpdate))
                .addContainerGap())
        );

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Salary", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 153, 0))); // NOI18N

        salaryUpdate.setText("Update");
        salaryUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryUpdateActionPerformed(evt);
            }
        });

        salaryView.setText("View");
        salaryView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addComponent(salaryView, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(salaryUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salaryView)
                    .addComponent(salaryUpdate))
                .addContainerGap())
        );

        jPanel22.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Service", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 153, 0))); // NOI18N

        serviceUpdate.setText("Update");
        serviceUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceUpdateActionPerformed(evt);
            }
        });

        serviceView.setText("View");
        serviceView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                .addComponent(serviceView, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(serviceUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serviceView)
                    .addComponent(serviceUpdate))
                .addContainerGap())
        );

        jPanel23.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CustomerLevel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 153, 0))); // NOI18N

        cusLevelUpdate.setText("Update");
        cusLevelUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusLevelUpdateActionPerformed(evt);
            }
        });

        cusLevelView.setText("View");
        cusLevelView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusLevelViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                .addComponent(cusLevelView, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cusLevelUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cusLevelView)
                    .addComponent(cusLevelUpdate))
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("User Name: ");

        jPanel24.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Permission", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 153, 0))); // NOI18N

        permissionUpdate.setText("Update");
        permissionUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                permissionUpdateActionPerformed(evt);
            }
        });

        permissionView.setText("View");
        permissionView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                permissionViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel24Layout.createSequentialGroup()
                .addComponent(permissionView, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(permissionUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(permissionView)
                    .addComponent(permissionUpdate))
                .addContainerGap())
        );

        jPanel25.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Employee", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 153, 0))); // NOI18N

        empUpdate.setText("Update");
        empUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empUpdateActionPerformed(evt);
            }
        });

        empView.setText("View");
        empView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel25Layout.createSequentialGroup()
                .addComponent(empView, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(empUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empView)
                    .addComponent(empUpdate))
                .addContainerGap())
        );

        jPanel26.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Suplier", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 153, 0))); // NOI18N

        supplierUpdate.setText("Update");
        supplierUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierUpdateActionPerformed(evt);
            }
        });

        supplierView.setText("View");
        supplierView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel26Layout.createSequentialGroup()
                .addComponent(supplierView, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(supplierUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supplierView)
                    .addComponent(supplierUpdate))
                .addContainerGap())
        );

        btClose.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/order/Delete2.png"))); // NOI18N
        btClose.setText("Close");
        btClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCloseActionPerformed(evt);
            }
        });

        btSelectAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/order/accept.png"))); // NOI18N
        btSelectAll.setText("Select All");
        btSelectAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelectAllActionPerformed(evt);
            }
        });

        btDeselectAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/order/crossout.png"))); // NOI18N
        btDeselectAll.setText("Deselect All");
        btDeselectAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeselectAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btClose, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblID1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btSelectAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(outbound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btDeselectAll, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btDeselectAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btSelectAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblID1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outbound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btClose, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setButton(boolean enabled) {
        btSave.setEnabled(enabled);
        btCancel.setEnabled(enabled);
        btSelectAll.setEnabled(enabled);
        btDeselectAll.setEnabled(enabled);
    }
//<editor-fold defaultstate="collapsed" desc="If else -- met vai linh hon">

    private void setCheckBox() {
        for (int i = 0; i < perList.size(); i++) {
//    System.out.println("User ID:  "+perList.get(i).toString());
            switch (perList.get(i).getFunctionID()) {
                case 1:
                    userView.setSelected(true);
                    break;
                case 2:
                    userUpdate.setSelected(true);
                    break;
                case 3:
                    permissionView.setSelected(true);
                    break;
                case 4:
                    permissionUpdate.setSelected(true);
                    break;
                case 5:
                    productView.setSelected(true);
                    break;
                case 6:
                    productUpdate.setSelected(true);
                    break;
                case 7:
                    branchView.setSelected(true);
                    break;
                case 8:
                    branchUpdate.setSelected(true);
                    break;
                case 9:
                    inboundView.setSelected(true);
                    break;
                case 10:
                    inboundUpdate.setSelected(true);
                    break;
                case 11:
                    outboundView.setSelected(true);
                    break;
                case 12:
                    outboundUpdate.setSelected(true);
                    break;
                case 13:
                    supplierView.setSelected(true);
                    break;
                case 14:
                    supplierUpdate.setSelected(true);
                    break;
                case 15:
                    orderView.setSelected(true);
                    break;
                case 16:
                    orderUpdate.setSelected(true);
                    break;
                case 17:
                    saleoffView.setSelected(true);
                    break;
                case 18:
                    saleoffUpdate.setSelected(true);
                    break;
                case 19:
                    cusView.setSelected(true);
                    break;
                case 20:
                    cusUpdate.setSelected(true);
                    break;
                case 21:
                    cusLevelView.setSelected(true);
                    break;
                case 22:
                    cusLevelUpdate.setSelected(true);
                    break;
                case 23:
                    serviceView.setSelected(true);
                    break;
                case 24:
                    serviceUpdate.setSelected(true);
                    break;
                case 25:
                    empView.setSelected(true);
                    break;
                case 26:
                    empUpdate.setSelected(true);
                    break;
                case 27:
                    salaryView.setSelected(true);
                    break;
                case 28:
                    salaryUpdate.setSelected(true);
                    break;
            }

        }
    }

    private void insertPermission() {
        if (userView.isSelected()) {
            permission = new Permission(user.getUserID(), 1);

            permissionDAOImpl.insert(permission);

        }
        if (userUpdate.isSelected()) {
            permission = new Permission(user.getUserID(), 2);
            permissionDAOImpl.insert(permission);
        }
        if (permissionView.isSelected()) {
            permission = new Permission(user.getUserID(), 3);
            permissionDAOImpl.insert(permission);
        }
        if (permissionUpdate.isSelected()) {
            permission = new Permission(user.getUserID(), 4);
            permissionDAOImpl.insert(permission);
        }
        if (productView.isSelected()) {
            permission = new Permission(user.getUserID(), 5);
            permissionDAOImpl.insert(permission);
        }
        if (productUpdate.isSelected()) {
            permission = new Permission(user.getUserID(), 6);
            permissionDAOImpl.insert(permission);
        }
        if (branchView.isSelected()) {
            permission = new Permission(user.getUserID(), 7);
            permissionDAOImpl.insert(permission);
        }
        if (branchUpdate.isSelected()) {
            permission = new Permission(user.getUserID(), 8);
            permissionDAOImpl.insert(permission);
        }
        if (inboundView.isSelected()) {
            permission = new Permission(user.getUserID(), 9);
            permissionDAOImpl.insert(permission);
        }
        if (inboundUpdate.isSelected()) {
            permission = new Permission(user.getUserID(), 10);
            permissionDAOImpl.insert(permission);
        }
        if (outboundView.isSelected()) {
            permission = new Permission(user.getUserID(), 11);
            permissionDAOImpl.insert(permission);
        }
        if (outboundUpdate.isSelected()) {
            permission = new Permission(user.getUserID(), 12);
            permissionDAOImpl.insert(permission);
        }
        if (supplierView.isSelected()) {
            permission = new Permission(user.getUserID(), 13);
            permissionDAOImpl.insert(permission);
        }
        if (supplierUpdate.isSelected()) {
            permission = new Permission(user.getUserID(), 14);
            permissionDAOImpl.insert(permission);
        }
        if (orderView.isSelected()) {
            permission = new Permission(user.getUserID(), 15);
            permissionDAOImpl.insert(permission);
        }
        if (orderUpdate.isSelected()) {
            permission = new Permission(user.getUserID(), 16);
            permissionDAOImpl.insert(permission);
        }
        if (saleoffView.isSelected()) {
            permission = new Permission(user.getUserID(), 17);
            permissionDAOImpl.insert(permission);
        }
        if (saleoffUpdate.isSelected()) {
            permission = new Permission(user.getUserID(), 18);
            permissionDAOImpl.insert(permission);
        }
        if (cusView.isSelected()) {
            permission = new Permission(user.getUserID(), 19);
            permissionDAOImpl.insert(permission);
        }
        if (cusUpdate.isSelected()) {
            permission = new Permission(user.getUserID(), 20);
            permissionDAOImpl.insert(permission);
        }
        if (cusLevelView.isSelected()) {
            permission = new Permission(user.getUserID(), 21);
            permissionDAOImpl.insert(permission);
        }
        if (cusLevelUpdate.isSelected()) {
            permission = new Permission(user.getUserID(), 22);
            permissionDAOImpl.insert(permission);
        }
        if (serviceView.isSelected()) {
            permission = new Permission(user.getUserID(), 23);
            permissionDAOImpl.insert(permission);
        }
        if (serviceUpdate.isSelected()) {
            permission = new Permission(user.getUserID(), 24);
            permissionDAOImpl.insert(permission);
        }
        if (empView.isSelected()) {
            permission = new Permission(user.getUserID(), 25);
            permissionDAOImpl.insert(permission);
        }
        if (empUpdate.isSelected()) {
            permission = new Permission(user.getUserID(), 26);
            permissionDAOImpl.insert(permission);
        }
        if (salaryView.isSelected()) {
            permission = new Permission(user.getUserID(), 27);
            permissionDAOImpl.insert(permission);
        }
        if (salaryUpdate.isSelected()) {
            permission = new Permission(user.getUserID(), 28);
            permissionDAOImpl.insert(permission);
        }

//        System.out.println("List: " + perList1.size());
    }

    public boolean checkChange() {
        return !(!userView.isSelected()
                || !userUpdate.isSelected()
                || !permissionView.isSelected()
                || !permissionUpdate.isSelected()
                || !productView.isSelected()
                || !productUpdate.isSelected()
                || !salaryView.isSelected()
                || !salaryUpdate.isSelected()
                || !saleoffUpdate.isSelected()
                || !saleoffView.isSelected()
                || !serviceUpdate.isSelected()
                || !serviceView.isSelected()
                || !supplierUpdate.isSelected()
                || !supplierView.isSelected()
                || !empUpdate.isSelected()
                || !empView.isSelected()
                || !cusLevelUpdate.isSelected()
                || !cusLevelView.isSelected()
                || !cusUpdate.isSelected()
                || !cusView.isSelected()
                || !orderUpdate.isSelected()
                || !orderView.isSelected()
                || !outboundUpdate.isSelected()
                || !outboundView.isSelected()
                || !inboundUpdate.isSelected()
                || !inboundView.isSelected()
                || !branchUpdate.isSelected()
                || !branchView.isSelected());
    }

    private void setCheckBoxEnable(boolean enabled) {
        userView.setEnabled(enabled);
        userUpdate.setEnabled(enabled);
        permissionView.setEnabled(enabled);
        permissionUpdate.setEnabled(enabled);
        productView.setEnabled(enabled);
        productUpdate.setEnabled(enabled);
        salaryView.setEnabled(enabled);
        salaryUpdate.setEnabled(enabled);
        saleoffUpdate.setEnabled(enabled);
        saleoffView.setEnabled(enabled);
        serviceUpdate.setEnabled(enabled);
        serviceView.setEnabled(enabled);
        supplierUpdate.setEnabled(enabled);
        supplierView.setEnabled(enabled);
        empUpdate.setEnabled(enabled);
        empView.setEnabled(enabled);
        cusLevelUpdate.setEnabled(enabled);
        cusLevelView.setEnabled(enabled);
        cusUpdate.setEnabled(enabled);
        cusView.setEnabled(enabled);
        orderUpdate.setEnabled(enabled);
        orderView.setEnabled(enabled);
        outboundUpdate.setEnabled(enabled);
        outboundView.setEnabled(enabled);
        inboundUpdate.setEnabled(enabled);
        inboundView.setEnabled(enabled);
        branchUpdate.setEnabled(enabled);
        branchView.setEnabled(enabled);
    }
//</editor-fold >

    public boolean isCkBoxChange(JCheckBox j, boolean old) {
        if (j.isSelected() == old) {
            return false;
        } else {
            return true;
        }
    }

    public void clearChkBox(boolean enabled) {
        userView.setSelected(enabled);
        userUpdate.setSelected(enabled);
        permissionView.setSelected(enabled);
        permissionUpdate.setSelected(enabled);
        productView.setSelected(enabled);
        productUpdate.setSelected(enabled);
        salaryView.setSelected(enabled);
        salaryUpdate.setSelected(enabled);
        saleoffUpdate.setSelected(enabled);
        saleoffView.setSelected(enabled);
        serviceUpdate.setSelected(enabled);
        serviceView.setSelected(enabled);
        supplierUpdate.setSelected(enabled);
        supplierView.setSelected(enabled);
        empUpdate.setSelected(enabled);
        empView.setSelected(enabled);
        cusLevelUpdate.setSelected(enabled);
        cusLevelView.setSelected(enabled);
        cusUpdate.setSelected(enabled);
        cusView.setSelected(enabled);
        orderUpdate.setSelected(enabled);
        orderView.setSelected(enabled);
        outboundUpdate.setSelected(enabled);
        outboundView.setSelected(enabled);
        inboundUpdate.setSelected(enabled);
        inboundView.setSelected(enabled);
        branchUpdate.setSelected(enabled);
        branchView.setSelected(enabled);
//        btOK.setEnabled(enabled);
    }
//<editor-fold defaultstate="collapsed" desc="cai dong action @@">   
    private void userUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userUpdateActionPerformed
        setButton(true);
    }//GEN-LAST:event_userUpdateActionPerformed

    private void productUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productUpdateActionPerformed
        setButton(true);
    }//GEN-LAST:event_productUpdateActionPerformed

    private void outboundUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outboundUpdateActionPerformed
        setButton(true);
    }//GEN-LAST:event_outboundUpdateActionPerformed

    private void inboundUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inboundUpdateActionPerformed
        setButton(true);
    }//GEN-LAST:event_inboundUpdateActionPerformed

    private void branchUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branchUpdateActionPerformed
        setButton(true);
    }//GEN-LAST:event_branchUpdateActionPerformed

    private void cusUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusUpdateActionPerformed
        setButton(true);
    }//GEN-LAST:event_cusUpdateActionPerformed

    private void saleoffUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleoffUpdateActionPerformed
        setButton(true);
    }//GEN-LAST:event_saleoffUpdateActionPerformed

    private void orderUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderUpdateActionPerformed
        setButton(true);
    }//GEN-LAST:event_orderUpdateActionPerformed

    private void salaryUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryUpdateActionPerformed
        setButton(true);
    }//GEN-LAST:event_salaryUpdateActionPerformed

    private void serviceUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceUpdateActionPerformed
        setButton(true);
    }//GEN-LAST:event_serviceUpdateActionPerformed

    private void cusLevelUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusLevelUpdateActionPerformed
        setButton(true);
    }//GEN-LAST:event_cusLevelUpdateActionPerformed

    private void permissionUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_permissionUpdateActionPerformed
        setButton(true);
    }//GEN-LAST:event_permissionUpdateActionPerformed

    private void empUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empUpdateActionPerformed
        setButton(true);
    }//GEN-LAST:event_empUpdateActionPerformed

    private void supplierUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierUpdateActionPerformed
        setButton(true);
    }//GEN-LAST:event_supplierUpdateActionPerformed

    private void saleoffViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleoffViewActionPerformed
        setButton(true);
    }//GEN-LAST:event_saleoffViewActionPerformed

    private void userViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userViewActionPerformed
        setButton(true);
    }//GEN-LAST:event_userViewActionPerformed

    private void permissionViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_permissionViewActionPerformed
        setButton(true);
    }//GEN-LAST:event_permissionViewActionPerformed

    private void productViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productViewActionPerformed
        setButton(true);
    }//GEN-LAST:event_productViewActionPerformed

    private void branchViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branchViewActionPerformed
        setButton(true);
    }//GEN-LAST:event_branchViewActionPerformed

    private void inboundViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inboundViewActionPerformed
        setButton(true);
    }//GEN-LAST:event_inboundViewActionPerformed

    private void outboundViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outboundViewActionPerformed
        setButton(true);
    }//GEN-LAST:event_outboundViewActionPerformed

    private void orderViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderViewActionPerformed
        setButton(true);
    }//GEN-LAST:event_orderViewActionPerformed

    private void cusViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusViewActionPerformed
        setButton(true);
    }//GEN-LAST:event_cusViewActionPerformed

    private void serviceViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceViewActionPerformed
        setButton(true);
    }//GEN-LAST:event_serviceViewActionPerformed

    private void empViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empViewActionPerformed
        setButton(true);
    }//GEN-LAST:event_empViewActionPerformed

    private void salaryViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryViewActionPerformed
        setButton(true);
    }//GEN-LAST:event_salaryViewActionPerformed

    private void cusLevelViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusLevelViewActionPerformed
        setButton(true);
    }//GEN-LAST:event_cusLevelViewActionPerformed

    private void supplierViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierViewActionPerformed
        setButton(true);
    }//GEN-LAST:event_supplierViewActionPerformed
//   </editor-fold>  
    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        if (isCkBoxChange(userUpdate, oldUser) || isCkBoxChange(permissionUpdate, oldPermission)) {
            if (permissionDAOImpl.checkRootPermission()) {
                permissionDAOImpl.delete(user);
                insertPermission();
                SwingUtils.showInfoDialog(SwingUtils.UPDATE_SUCCESS);
                dispose();
            } else {
                SwingUtils.showErrorDialog("Only ADMIN ROOT can set permission: UPDATE PERMISSION & UPDATE USER !");
                clearChkBox(false);
                setCheckBox();
                setButton(false);
                btSelectAll.setEnabled(true);
                btDeselectAll.setEnabled(true);
                return;
            }
        } else if (EmployeeSwingUtils.showConfirmDialog("Are you sure to update ?") == JOptionPane.NO_OPTION) {
            return;
        } else {
            permissionDAOImpl.delete(user);
            insertPermission();
            dispose();
            SwingUtils.showInfoDialog(SwingUtils.UPDATE_SUCCESS);            
        }
    }//GEN-LAST:event_btSaveActionPerformed

    private void btCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btCloseActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        clearChkBox(false);
        setCheckBox();
    }//GEN-LAST:event_btCancelActionPerformed

    private void btSelectAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelectAllActionPerformed
        if (LoginFrame.config.userName.equals("root")) {
            clearChkBox(true);
            setButton(true);
        } else {
            clearChkBox(true);
            userUpdate.setSelected(false);
            permissionUpdate.setSelected(false);
            setButton(true);
        }
    }//GEN-LAST:event_btSelectAllActionPerformed

    private void btDeselectAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeselectAllActionPerformed
        clearChkBox(false);
        setButton(true);
    }//GEN-LAST:event_btDeselectAllActionPerformed

//   <editor-fold>  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox branchUpdate;
    private javax.swing.JCheckBox branchView;
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btClose;
    private javax.swing.JButton btDeselectAll;
    private javax.swing.JButton btSave;
    private javax.swing.JButton btSelectAll;
    private javax.swing.JCheckBox cusLevelUpdate;
    private javax.swing.JCheckBox cusLevelView;
    private javax.swing.JCheckBox cusUpdate;
    private javax.swing.JCheckBox cusView;
    private javax.swing.JCheckBox empUpdate;
    private javax.swing.JCheckBox empView;
    private javax.swing.JCheckBox inboundUpdate;
    private javax.swing.JCheckBox inboundView;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lblID1;
    private javax.swing.JCheckBox orderUpdate;
    private javax.swing.JCheckBox orderView;
    private javax.swing.JPanel outbound;
    private javax.swing.JCheckBox outboundUpdate;
    private javax.swing.JCheckBox outboundView;
    private javax.swing.JCheckBox permissionUpdate;
    private javax.swing.JCheckBox permissionView;
    private javax.swing.JCheckBox productUpdate;
    private javax.swing.JCheckBox productView;
    private javax.swing.JCheckBox salaryUpdate;
    private javax.swing.JCheckBox salaryView;
    private javax.swing.JCheckBox saleoffUpdate;
    private javax.swing.JCheckBox saleoffView;
    private javax.swing.JCheckBox serviceUpdate;
    private javax.swing.JCheckBox serviceView;
    private javax.swing.JCheckBox supplierUpdate;
    private javax.swing.JCheckBox supplierView;
    private javax.swing.JCheckBox userUpdate;
    private javax.swing.JCheckBox userView;
    // End of variables declaration//GEN-END:variables
}
//        </editor-fold>  
